language: c++
sudo: false
dist: trusty

addons:
  apt:
    packages:
      - g++-6
    sources:
      - ubuntu-toolchain-r-test

matrix:
  include:
    - os: linux
      compiler: gcc-6

script:
  - export CXX=g++-6
  - mkdir x
  - cd x
  - cmake ..
  - make VERBOSE=1
  - ./example/http_client
