language: c++

matrix:
  include:

    - os: linux
      env: BUILD_TYPE="vanilla"
      script:
        - ./.ci/docker/script/docker-run bassosimone/mk-debian:testing cmake
      services:
        - docker
      sudo: required

    - os: linux
      env: BUILD_TYPE="coverage"
           CFLAGS="-O0 -g -fprofile-arcs -ftest-coverage"
           COVERALLS_OPTIONS="--include include --include src --include example"
           CXXFLAGS="-O0 -g -fprofile-arcs -ftest-coverage"
           LDFLAGS="-lgcov"
      script:
        - ./.ci/docker/script/docker-run bassosimone/mk-debian:testing cmake
      services:
        - docker
      sudo: required
