language: c++
sudo: false
dist: trusty

addons:
  apt:
    packages:
      - g++-7
    sources:
      - ubuntu-toolchain-r-test

matrix:
  include:
    - os: linux
      compiler: gcc-7

script:
  - export CXX=g++-7
  - mkdir x
  - cd x
  - cmake ..
  - make
  - ./example/http_client
